<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-T4MFR2V" failures="2" tests="10" name="TestNGFramwork.TestNGSevenPm.AssertionTest" time="0.029" errors="0" timestamp="25 Apr 2023 14:10:10 GMT" skipped="6">
  <testcase classname="TestNGFramwork.TestNGSevenPm.AssertionTest" name="test3" time="0.001">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="TestNGFramwork.TestNGSevenPm.AssertionTest" name="test4" time="0.002"/>
  <testcase classname="TestNGFramwork.TestNGSevenPm.AssertionTest" name="test3" time="0.001">
    <failure message="The following asserts failed:
	expected [TestNG] but found [Cucumber]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [TestNG] but found [Cucumber]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at TestNGFramwork.TestNGSevenPm.AssertionTest.test3(AssertionTest.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="TestNGFramwork.TestNGSevenPm.AssertionTest" name="test3" time="0.010">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="TestNGFramwork.TestNGSevenPm.AssertionTest" name="test1" time="0.002">
    <failure message="expected [Selenium ] but found [Java]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Selenium ] but found [Java]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at TestNGFramwork.TestNGSevenPm.AssertionTest.test1(AssertionTest.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="TestNGFramwork.TestNGSevenPm.AssertionTest" name="test2" time="0.003"/>
  <testcase classname="TestNGFramwork.TestNGSevenPm.AssertionTest" name="test1" time="0.002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="TestNGFramwork.TestNGSevenPm.AssertionTest" name="test1" time="0.004">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="TestNGFramwork.TestNGSevenPm.AssertionTest" name="test1" time="0.002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="TestNGFramwork.TestNGSevenPm.AssertionTest" name="test3" time="0.002">
    <skipped/>
  </testcase> <!-- test3 -->
</testsuite> <!-- TestNGFramwork.TestNGSevenPm.AssertionTest -->
